### ISSUE TITLE
v3.5.2 Release Checklist

### ISSUE THREAD

**Issue by jcramer** [simpleledger/Electron-Cash-SLP#103]
- [x] Prompt user at startup to connect to a gs++ server for fast trustless validation
- [x] Resolve proxy issue with graph search grpc connection
- [x] If job is invalid using GS data set, then re-attempt validation using fallback data source (i.e., ElectrumX)
- [x] Remove "Depth Progress" from network dialog
- [x] Remove "port" property from gs list
- [x] Rename SLPDB to gs++ in ui parts
- [x] Resolve multi-sig burn signing issue with Electron Cash SLP
- [x] Fix caps lock issue on seed entry
- [x] Fix issue with changing address format on window minimization

**Comment by cculianu** [comment]
What signing issue is that? For macOS? or is that something else?

**Comment by cculianu** [comment]
Regarding the proxy issue: Not possible using google's `grpc` library.  May be possible using the non-google python-only `grpclib` -- but that uses asyncio and would require a bit of redesign of the `GraphSearchMgr` object to plug nicely into `async` and `await` etc...
