### ISSUE TITLE
James' Task List

### ISSUE THREAD

**Issue by jcramer** [simpleledger/Electron-Cash-SLP#2]
- [x] Upgrade op_return tool with `<push>`, `<hex>` and `<empty>` annotations
- [x] Add methods to slp.py for building GENESIS and SEND op_return messages
- [x] Prevent token (valid or invalid) from being spent in normal BCH transaction or in other token TXNs
- [x] Add detection of TXOs created from GENESIS and SEND type transactions 
- [x] Remove comment field from SEND message
- [x] Fix behavior of "amount_e" and "max_button" controls in token mode
- [x] Use 0x4c 0x00 for null data fields (instead of pushing 0x00)
- [x] Add token id to dropdown for incoming token transactions
- [x] Add decimal field in GENESIS message per the spec
- [x] Add "baton_vout" field to GENESIS message
- [x] Send SLP tokens from op_return SEND message
- [x] Handle token chooser & change output for SLP tokens based on token amount being sent
- [x] Add UI validation for SLP amount (token amount to be spent cannot be greater than available token balance; display validated balance / unvalidated balance)
- [x] Output amount does not update to token amount (546 sat) after being previously set to Max.
- [x] Persist `slp_txo` data to new wallet.json section called "slp_txo" (renamed from slp_utxo)
- [x] Coins tab is showing tokens only sometimes (determine desired behavior)
- [x] Update all SLP code paths to be disabled upon setting in config
- [x] Handle GENESIS & MINT Batons in slp_txo 
- [x] Add UI for GENESIS & MINT txns
- [x] Handle decimal precision for GENESIS gui
- [x] test value overflow conditions in txn (add multiple outputs when output quantity exceeds X)
- [x] Handle decimal precision for MINT gui
- [x] add max and "!" shortcut to token amount box
- [x] tighten up field size requirements in slp.py
- [x] rename transaction types (GENESIS, MINT, SEND)
- [x] token tab balance does not update immediately
- [x] automatically add token to Tokens tab after creating a new token.
- [ ] add BATON txn to SLP History
- [x] Provide some UI indicating how to create a new token
- [x] Show baton indication in Tokens tab
- [ ] one slightly annoying thing with mint when doing HUGE amounts — every time I add / remove a digit to the entry field, it pops up a new warning popup message
- [x] update token Ticker in slp amount box in MINT form
- [x] SLP enabled by default?
- [x] GENESIS dust limit sometimes is an issue with coin chooser

Wish List:
- [ ] pay [bch] to token holders feature (x bch per token held)
- [ ] Reduce fee in MINT transaction
- [x] Pre-check incoming txn for LokadId and type_id before initiating parser
- [x] allow any token_type in slp_txo
- [ ] show the total issued amount (GENESIS + MINT txns)
- [x] add a secondary check for detecting token inputs within a transaction, warn user
