### ISSUE TITLE
Mark's Todo list

### ISSUE THREAD

**Issue by markblundeberg** [simpleledger/Electron-Cash-SLP#5]
- [x] (other repo) write blurb on SLP validation algorithm.
- [x] Use wallet persisted validity results in DAG runs on future startups.
- [x] Start up validator acting on unknown-validity txes, upon wallet loading or SLP enablement.
- [ ] Caching of all validity judgements discovered during DAG, but make sure it's optional.
- [x] Enforce download limit.
- [x] Put in framework for supporting proxy queries and appropriate insertion of proxy answers when we truncate DAG search.
- [x] MINTs not yet functional
- [x] Validator should not run on unknown token_ids
- [x] Make slp_tokens config stuff into a id-keyed dict instead.
- [x] Validator isn't notifying UI on completion.
- [x] Create callback structures in wallet where UI can get pinged on update. (cf main_window.py lines 212-227)
- [x] Never ever run validator when not config.get('enable_slp')
- [x] Make sure wallet doesn't spent SLP coins of unknown token_type.
- [ ] Rename token_types
- [x] Decimals in mint/init gui.
- [x] Fix rounding in slpamountedit (via format_satoshis_plain).
- [x] Spec edit - remove remaining_mint_allowed
- [x] Spec edit - move consensus rules into one place
- [ ] Spec edit - notes on wallets handling different SLP versions
- [x] qt event notify from validator: slp history tab, tokens tab (balances), status bar
- [ ] Add unit tests with various encodings of 'SEND' and lokad ID. 'SEND': 'U0VORA==' (base64), '53454e44' (hex) 'SEND\x00', ...
- [ ] Tests for MINT-MINT baton passing
- [x] Tests to ensure 'address balance' is not used.
- [ ] More tests relating to token output amount truncation / extension.
- [ ] Test with nonzero bch amount for op_return / other outputs.
- [ ] Test that spends from an implicit '0' output.
- [x] Use ":" for icons
- [ ] When we have proxy answers, compare them to DAG judgements and warn on disagreement.

Wishlist:
- [ ] Have a thing in preferences to control SLP validator - proxy URL, request limits.
- [ ] Have a thing in the tx dialog that lets you look at SLP info.
- [ ] Human friendly unicode strings should use ord() to count uglies, not bytes.
