### ISSUE TITLE
Pre-launch Checklist

### ISSUE THREAD

**Issue by jcramer** [simpleledger/Electron-Cash-SLP#7]
- [ ] remove op_return attribute features
- [ ] should have full code review of all changes
- [ ] all unit tests running
- [ ] live alpha testing with volunteers
- [ ] website, checked on several browsers and devices
- [ ] executables built and signed
